# Generated by Django 2.2.5 on 2019-09-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-create_time']},
        ),
    ]
