# Generated by Django 2.2.5 on 2019-09-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190919_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
