# Generated by Django 2.2.5 on 2019-09-22 01:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190919_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='context',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
